/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abenantelutzengestionegara;

/**
 *
 * @author abenante.lucia
 */
public class AggiungiGitaGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiungiGitaGUI.class.getName());
private LogicaGita l;
    private GestioneGitaGUI finestraPrincipale;
    /**
     * Creates new form AggiungiGaraGUI
     */
    public AggiungiGitaGUI(LogicaGita l, GestioneGitaGUI finestraPrincipale) {
        this.l = l;
        this.finestraPrincipale = finestraPrincipale;
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblLocalita = new javax.swing.JLabel();
        lblDurata = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtLocalita = new javax.swing.JTextField();
        txtDurata = new javax.swing.JTextField();
        btnAggiungi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(236, 119, 16));

        lblID.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblID.setText("ID");

        lblLocalita.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblLocalita.setText("Località");

        lblDurata.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblDurata.setText("Durata");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocalita, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDurata, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDurata)
                    .addComponent(txtLocalita, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtID))
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalita)
                    .addComponent(txtLocalita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDurata)
                    .addComponent(txtDurata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 100, 470, 220);

        btnAggiungi.setBackground(new java.awt.Color(236, 119, 16));
        btnAggiungi.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });
        jPanel1.add(btnAggiungi);
        btnAggiungi.setBounds(160, 340, 120, 70);

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel4.setText("Crea una Gita");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 20, 180, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
      // La GUI legge i campi e passa i valori grezzi alla logica
        String esito = l.aggiungiGita(
            txtID.getText().trim(),
            txtLocalita.getText().trim(),
            txtDurata.getText().trim()
        );

        javax.swing.JOptionPane.showMessageDialog(this,
            esito.replace("OK: ", "").replace("ERRORE: ", ""));

        if (esito.startsWith("OK")) {
            // Aggiorna la combobox e la tabella nella finestra principale
            finestraPrincipale.aggiornaComboGite();
            // Pulisce i campi per un eventuale nuovo inserimento
            txtID.setText("");
            txtLocalita.setText("");
            txtDurata.setText("");
        } 
	  
	  
    }//GEN-LAST:event_btnAggiungiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDurata;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblLocalita;
    private javax.swing.JTextField txtDurata;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLocalita;
    // End of variables declaration//GEN-END:variables
}