/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abenantelutzengestionegara;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author abenante.lucia
 */
public class AggiungiStudenteGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiungiStudenteGUI.class.getName());
private LogicaGita l;
    private GestioneGitaGUI finestraPrincipale;
    /**
     * Creates new form AggiungiStudenteGUI
     */
    public AggiungiStudenteGUI(LogicaGita l, GestioneGitaGUI finestraPrincipale) {
        this.l = l;
        this.finestraPrincipale = finestraPrincipale;
		initComponents();
        Controlli c = new Controlli();
		  caricaComboGite();
    }
//metodi
/**
     * Popola la combobox con le gite lette dal file tramite LogicaGita.
     */
    private void caricaComboGite() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (String voce : l.getVociComboGite()) {
            model.addElement(voce);
        }
        cbxGita.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAggiungi = new javax.swing.JButton();
        lblTitolo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblMatricola = new javax.swing.JLabel();
        lblAnno = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        txtMatricola = new javax.swing.JTextField();
        txtAnno = new javax.swing.JTextField();
        lblIdGita = new javax.swing.JLabel();
        cbxGita = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(null);

        btnAggiungi.setBackground(new java.awt.Color(102, 255, 102));
        btnAggiungi.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });
        jPanel1.add(btnAggiungi);
        btnAggiungi.setBounds(150, 410, 120, 50);

        lblTitolo.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lblTitolo.setText("Crea uno Studente");
        jPanel1.add(lblTitolo);
        lblTitolo.setBounds(90, 10, 220, 40);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));
        jPanel2.setLayout(null);

        lblNome.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblNome.setText("Nome");
        jPanel2.add(lblNome);
        lblNome.setBounds(50, 20, 60, 30);

        lblCognome.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblCognome.setText("Cognome");
        jPanel2.add(lblCognome);
        lblCognome.setBounds(40, 80, 90, 30);

        lblMatricola.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblMatricola.setText("Matricola");
        jPanel2.add(lblMatricola);
        lblMatricola.setBounds(40, 140, 90, 30);

        lblAnno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblAnno.setText("Anno");
        jPanel2.add(lblAnno);
        lblAnno.setBounds(50, 200, 60, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome);
        txtNome.setBounds(250, 20, 140, 22);
        jPanel2.add(txtCognome);
        txtCognome.setBounds(250, 80, 140, 22);

        txtMatricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatricolaActionPerformed(evt);
            }
        });
        jPanel2.add(txtMatricola);
        txtMatricola.setBounds(250, 140, 140, 22);

        txtAnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtAnno);
        txtAnno.setBounds(250, 200, 140, 22);

        lblIdGita.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblIdGita.setText("Id Gita");
        jPanel2.add(lblIdGita);
        lblIdGita.setBounds(40, 250, 70, 30);

        cbxGita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxGita);
        cbxGita.setBounds(250, 260, 140, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 440, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtMatricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatricolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatricolaActionPerformed

    private void txtAnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnoActionPerformed

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
     if (cbxGita.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nessuna gita disponibile.");
            return;
        }

        int idGita = l.estraiIdDaVoceCombo(cbxGita.getSelectedItem().toString());

        // La GUI legge i campi e passa tutto alla logica
        String esito = l.aggiungiStudente(
            txtNome.getText().trim(),
            txtCognome.getText().trim(),
            txtMatricola.getText().trim(),
            txtAnno.getText().trim(),
            idGita
        );

        javax.swing.JOptionPane.showMessageDialog(this,
            esito.replace("OK: ", "").replace("ERRORE: ", ""));

        if (esito.startsWith("OK")) {
            // Aggiorna la tabella nella finestra principale se la gita selezionata coincide
            finestraPrincipale.aggiornaTabella();
            // Pulisce i campi
            txtNome.setText("");
            txtCognome.setText("");
            txtMatricola.setText("");
            txtAnno.setText("");
        }
    }//GEN-LAST:event_btnAggiungiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JComboBox<String> cbxGita;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnno;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblIdGita;
    private javax.swing.JLabel lblMatricola;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtMatricola;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}