/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abenantelutzengestionegara;

/**
 *
 * @author abenante.lucia
 */
public class AggiungiStudenteGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiungiStudenteGUI.class.getName());

    /**
     * Creates new form AggiungiStudenteGUI
     */
    public AggiungiStudenteGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAggiungi = new javax.swing.JButton();
        lblTitolo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblMatricola = new javax.swing.JLabel();
        lblAnno = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        txtMatricola = new javax.swing.JTextField();
        txtAnno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(null);

        btnAggiungi.setBackground(new java.awt.Color(51, 255, 51));
        btnAggiungi.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        btnAggiungi.setText("Aggiungi");
        jPanel1.add(btnAggiungi);
        btnAggiungi.setBounds(130, 350, 120, 50);

        lblTitolo.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        lblTitolo.setForeground(new java.awt.Color(51, 255, 51));
        lblTitolo.setText("Crea un Studente");
        jPanel1.add(lblTitolo);
        lblTitolo.setBounds(90, 10, 220, 40);

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setLayout(null);

        lblNome.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblNome.setText("Nome");
        jPanel2.add(lblNome);
        lblNome.setBounds(50, 20, 60, 30);

        lblCognome.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblCognome.setText("Cognome");
        jPanel2.add(lblCognome);
        lblCognome.setBounds(40, 80, 90, 30);

        lblMatricola.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblMatricola.setText("Matricola");
        jPanel2.add(lblMatricola);
        lblMatricola.setBounds(40, 140, 90, 30);

        lblAnno.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        lblAnno.setText("Anno");
        jPanel2.add(lblAnno);
        lblAnno.setBounds(50, 200, 60, 20);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel2.add(txtNome);
        txtNome.setBounds(210, 20, 140, 22);
        jPanel2.add(txtCognome);
        txtCognome.setBounds(210, 80, 140, 22);

        txtMatricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatricolaActionPerformed(evt);
            }
        });
        jPanel2.add(txtMatricola);
        txtMatricola.setBounds(210, 140, 140, 22);

        txtAnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtAnno);
        txtAnno.setBounds(209, 200, 140, 22);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 80, 400, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtMatricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatricolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatricolaActionPerformed

    private void txtAnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AggiungiStudenteGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnno;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblMatricola;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JTextField txtAnno;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtMatricola;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
