/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abenantelutzengestionegara;

/**
 *
 * @author abenante.lucia
 */
public class AggiungiStudenteGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AggiungiStudenteGUI.class.getName());

    /**
     * Creates new form AggiungiStudenteGUI
     */
    public AggiungiStudenteGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblMatricola = new javax.swing.JLabel();
        lblAnno = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        txtMatricola = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnno = new javax.swing.JTextPane();
        btnAggiungi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblNome.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        lblNome.setText("Nome");
        jPanel1.add(lblNome);
        lblNome.setBounds(20, 40, 40, 23);

        lblCognome.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        lblCognome.setText("Cognome");
        jPanel1.add(lblCognome);
        lblCognome.setBounds(10, 100, 70, 23);

        lblMatricola.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        lblMatricola.setText("Matricola");
        jPanel1.add(lblMatricola);
        lblMatricola.setBounds(10, 170, 70, 23);

        lblAnno.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        lblAnno.setText("Anno");
        jPanel1.add(lblAnno);
        lblAnno.setBounds(20, 230, 40, 23);

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(140, 40, 140, 22);
        jPanel1.add(txtCognome);
        txtCognome.setBounds(140, 100, 140, 22);

        txtMatricola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatricolaActionPerformed(evt);
            }
        });
        jPanel1.add(txtMatricola);
        txtMatricola.setBounds(140, 170, 140, 22);

        jScrollPane1.setViewportView(txtAnno);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 230, 140, 22);

        btnAggiungi.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        btnAggiungi.setText("Aggiungi");
        jPanel1.add(btnAggiungi);
        btnAggiungi.setBounds(100, 290, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtMatricolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatricolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatricolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AggiungiStudenteGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnno;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblMatricola;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextPane txtAnno;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtMatricola;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
